version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:$PGDATA
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge
